---
title: "Interactive components"
output:
  html_document:
    df_print: paged
    code_folding: "hide"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(vroom)
library(shiny)
library(sf)
library(tigris)
library(tmap)
```

## Interactive map

```{r}
state_utilization <- vroom("https://healthdata.gov/api/views/6xf2-c3ie/rows.csv?accessType=DOWNLOAD")

us_states <- states(cb = TRUE, resolution = "20m", progress_bar = FALSE)

conus <- us_states %>% 
  filter(NAME %in% setdiff(state.name, c("Hawaii", "Alaska"))) %>% 
  st_bbox()
```

```{r}
state_utilization_metrics <-  state_utilization %>% 
  # Staffing shortage metrics
  mutate(
    percent_staffing_shortage_today = critical_staffing_shortage_today_yes/(critical_staffing_shortage_today_yes + critical_staffing_shortage_today_no),
    percent_staffing_shortage_anticipated_within_week = critical_staffing_shortage_anticipated_within_week_yes/(critical_staffing_shortage_anticipated_within_week_yes + critical_staffing_shortage_anticipated_within_week_no)
  ) %>% 
  # For labels
  mutate(
    shortage = paste(critical_staffing_shortage_today_yes, critical_staffing_shortage_today_yes +  critical_staffing_shortage_today_no, sep = "/"),
    anticipated_shortage = paste(critical_staffing_shortage_anticipated_within_week_yes, critical_staffing_shortage_anticipated_within_week_yes +  critical_staffing_shortage_anticipated_within_week_no, sep = "/"),
  )
```

```{r eval = FALSE, echo = FALSE}
glimpse(state_utilization_metrics)

metric_choices <- setNames(
  c("percent_staffing_shortage", "inpatient_beds_utilization"),
  c("% Staffing Shortage", "Inpatient bed utilization")
)
  
# metric_choices <- c("perc_staffing_shortage", "inpatient_beds_utilization")

# c("% Staffing Shortage", "Inpatient bed utilization", "")
# c("percent_staffing_shortage", "perc_anticipated_shoratge", "staffed_adult_icu_bed_occupancy", "inpatient_beds_utilization", "inpatient_bed_covid_utilization", "adult_icu_bed_utilization")
```


```{r}

shortage_choices <- setNames(
  c("percent_staffing_shortage_today", "percent_staffing_shortage_anticipated_within_week"),
  c("% Staffing Shortage Today", "% Anticipated Shortage Next Week")
)

radioButtons("expected_shortage", NULL,
             choices = shortage_choices)
```

```{r}
renderTmap({
  us_states %>% 
    left_join(state_utilization_metrics, by = c("STUSPS" = "state")) %>% 
    tm_shape(bbox = conus) +
    tm_polygons(input$expected_shortage, 
                title = names(shortage_choices)[which(input$expected_shortage == shortage_choices)],
                id = "NAME", palette = "Oranges",
                popup.vars = c(
                  "Hospitals with staffing shortage" = "shortage",
                  "Hospitals anticipating shortage" = "anticipated_shortage"
                  
                )
    )
})
```

## State/County Breakdown

```{r eval=FALSE}
# Load data 
df <- vroom(here::here("data","reported_patient_impact_hospital_capacity_facility.csv")) %>% 
  select(hospital_pk:is_metro_micro, inpatient_beds_7_day_sum, 
       ends_with("avg"), starts_with("previous"),
       geocoded_hospital_address) 

# Keep locations in separate dataframe
locations <- df %>%
  distinct(hospital_pk, state, city, address, zip, geocoded_hospital_address) %>% 
  replace_na(list(geocoded_hospital_address = "POINT EMPTY")) %>%
  st_as_sf(wkt = "geocoded_hospital_address", na.fail = FALSE)

df <- df %>% 
  select(-c(state, city, address, zip, geocoded_hospital_address))

# Impute -999999 values
impute_999999_values <- function(df, formule) {
  df[rlang::as_function(formule)(df)] <- 0
  df
}

df <- df %>% 
  impute_999999_values(~ .x == -999999)
```

```{r eval=FALSE}
hospital_metrics <- df %>% 
  mutate(
    # Hospital admissions
    hospital_admissions = previous_day_admission_adult_covid_confirmed_7_day_sum + previous_day_admission_adult_covid_suspected_7_day_sum +  previous_day_admission_pediatric_covid_confirmed_7_day_sum + previous_day_admission_pediatric_covid_suspected_7_day_sum,
    # % Hospital beds occupied by COVID-19 patients
    beds_covid_occupied = (total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg + total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg)/inpatient_beds_7_day_avg,
    # % Inpatient beds occupied by adult COVID patients
    inpatient_beds_covid_occupied = total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg/ all_adult_hospital_inpatient_beds_7_day_avg,
    # % Adult inpatient care that are COVID patient
    inpatient_care_covid_prop = total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg /all_adult_hospital_inpatient_bed_occupied_7_day_avg,
    # % Staffed adult ICU bed usage (COVID and non-COVID occupied)
    icu_capacity_used = staffed_adult_icu_bed_occupancy_7_day_avg/ total_staffed_adult_icu_beds_7_day_avg,
    # % Staffed adult ICU bed usage (COVID occupied only)
    icu_capacity_covid_used = staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg/ total_staffed_adult_icu_beds_7_day_avg,
    # New COVID cases confirmed or suspected in the past week
    new_cases_confirmed_or_suspected = previous_day_admission_adult_covid_confirmed_7_day_sum + previous_day_admission_adult_covid_suspected_7_day_sum
  ) %>% 
  select(hospital_pk:is_metro_micro, inpatient_beds_7_day_avg, hospital_admissions:last_col())
```


```{r}
# These are statistics for past 7 days
metric_choices <- setNames(
  c("cases_last_7_days", "cases_per_100k_last_7_days", "cases_pct_change_from_prev_week",
    "deaths_last_7_days", "deaths_per_100k_last_7_days", "deaths_pct_change_from_prev_week",
    "test_positivity_rate_last_7_days", "test_positivity_rate_pct_change_from_prev_week",
    "confirmed_covid_hosp_per_100_beds_last_7_days", "confirmed_covid_hosp_per_100_beds_pct_change_from_prev_week",
    "pct_inpatient_beds_used_covid_avg_last_7_days", "pct_inpatient_beds_used_covid_abs_change_from_prev_week",
    "pct_icu_beds_used_covid_avg_last_7_days", "pct_icu_beds_used_covid_abs_change_from_prev_week"),
    c("Cases", "Cases per 100k", "% Change in Cases per 100k",
    "Deaths", "Deaths per 100k", "% Change in Cases per 100k",
    "Viral (RT-PCR) Lab Test Positivity", "Change in Viral Lab Test Positivity",
    "COVID-19 Confirmed Hospital Admissions per 100 beds", "% Change in Confirmed COVID-19 Admissions per 100 beds",
    "Hospital Inpatient Utilization for COVID-19 Patients", "Change in Inpatient Utilization for COVID-19 Patients",
    "Adult ICU Utilization for COVID-19 Patients", "Change in Adult ICU Utilization for COVID-19 Patients")
)
```

```{r}
selectInput("state", "Choose state", setNames(c("All", state.abb), c("All", state.name)))
selectInput("metric", "Choose metric", metric_choices)
```

```{r}
df_tbl <- vroom(here::here("data", "cpr_county.csv"))
us_counties <- counties(cb = TRUE, resolution = "20m", progress_bar = FALSE) %>% 
  mutate(fips = as.numeric(paste0(STATEFP, COUNTYFP)))

# tmap_mode("view")
renderTmap({
  us_counties %>% 
    left_join(df_tbl) %>%
    filter(if (input$state == "All") TRUE else input$state == state) %>% 
    tm_shape(bbox = if (input$state == "All") conus else NULL) +
    tm_polygons(input$metric,
                title = names(metric_choices)[which(input$metric == metric_choices)],
                id = "NAME")
})

```


